// api.js — single entry point for talking to the backend.
//
// Re-exports the Wails-generated bindings (so view modules do not
// need to know the wailsjs path) and adds a couple of HTTP helpers
// for the agent endpoints that are not yet wrapped on the Go side
// (status XML, radio search, etc.).

export {
  DiscoverBoxes,
  RefreshKnownBoxes,
  GetPresets,
  SetPreset,
  DeletePreset,
  PlaySlot,
  PlayURL,
  StartQueue,
  QueueNext,
  QueuePrev,
  QueueShuffle,
  QueueRepeat,
  GetQueue,
  VoteStation,
  RebootBox,
  SyncBoxPresets,
  BoxPresets,
  BoxSnapshot,
  RestoreBoxSnapshot,
  RecallBoxPreset,
  CopyPresetsAcrossBoxes,
  GetBoxFirmware,
  BoxInstallReachable,
  Pause,
  Resume,
  Stop,
  Status,
  ListDrives,
  WriteStickFiles,
  FormatStick,
  StickVersion,
  CheckStick,
  StickConfigs,
  AppInfo,
  EjectDrive,
  BoxAgentVersion,
  UpdateBoxAgent,
  WriteWLANConfig,
  WriteRegionConfig,
  WriteNameConfig,
  WriteLangConfig,
  SetAppLocale,
  SuggestBoxLanguage,
  ListWiFiProfiles,
  TryWiFiPassword,
  CurrentWiFi,
  CheckAppUpdate,
  ResolveStationLogo,
  BoxSettings,
  SetBoxName,
  SetBoxVolume,
  SetBoxBass,
  SelectBoxSource,
  GetClockDisplay,
  SetClockDisplay,
  GetClockFormat24,
  GetBoxLanguage,
  SetBoxLanguage,
  GetAirplayOpt,
  SetAirplayOpt,
  GetResumeOnPowerOn,
  SetResumeOnPowerOn,
  GetDisplayTrack,
  SetDisplayTrack,
  AnnounceExample,
  SendAnnounce,
  Translate,
  ResolveUpdateAsset,
  DownloadUpdate,
  ApplyUpdate,
  RevealUpdateFile,
  GetAppFlag,
  SetAppFlag,
  RescuedSpeakerCount,
  GetWebhooks,
  SetWebhooks,
  SaveWebhookConfig,
  TestWebhook,
  TestWebhookAction,
  StreamBitrate,
  StreamTitle,
  SpotifyBitrate,
  SpotifyNowPlaying,
  SaveSpotifyPreset,
  SaveLibraryPreset,
  SaveFolderPreset,
  RecentPlayed,
  ClearRecent,
  DeleteRecentCard,
  SaveDiagnosticBundle,
  GetLogFilePath,
  InstallSTROnBox,
  RepairInstallViaSSH,
  RadioSearch,
  RadioTags,
  RadioLanguages,
  RadioVote,
  RadioClick,
  TrueFactoryReset,
  UninstallSTR,
  ProbeSetupAP,
  PushWLANToBox,
  ListMediaServers,
  BrowseLibrary,
  LogClientError,
  GetZoneState,
  FormZone,
  DissolveZone,
  SyncSpotifyLogin,
} from '../wailsjs/go/main/App';

export { BrowserOpenURL, EventsOn, EventsOff } from '../wailsjs/runtime/runtime';

// boxURL builds an absolute URL for an agent endpoint on a given box.
// Centralised so the host/port pattern is in one place and switching
// to HTTPS later only takes touching this helper.
export function boxURL(box, path) {
  if (!box) return '';
  return `http://${box.host}:${box.port}${path}`;
}
