// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BoxAgentVersion(arg1, arg2) {
  return window['go']['main']['App']['BoxAgentVersion'](arg1, arg2);
}

export function BoxSettings(arg1, arg2) {
  return window['go']['main']['App']['BoxSettings'](arg1, arg2);
}

export function BrowseLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseLibrary'](arg1, arg2, arg3, arg4);
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function CurrentWiFi() {
  return window['go']['main']['App']['CurrentWiFi']();
}

export function DeletePreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePreset'](arg1, arg2, arg3);
}

export function DiscoverBoxes(arg1) {
  return window['go']['main']['App']['DiscoverBoxes'](arg1);
}

export function EjectDrive(arg1) {
  return window['go']['main']['App']['EjectDrive'](arg1);
}

export function ExportDiagnosticLogs(arg1) {
  return window['go']['main']['App']['ExportDiagnosticLogs'](arg1);
}

export function FormatStick(arg1) {
  return window['go']['main']['App']['FormatStick'](arg1);
}

export function GetBoxLanguage(arg1) {
  return window['go']['main']['App']['GetBoxLanguage'](arg1);
}

export function GetClockDisplay(arg1) {
  return window['go']['main']['App']['GetClockDisplay'](arg1);
}

export function GetClockFormat24(arg1) {
  return window['go']['main']['App']['GetClockFormat24'](arg1);
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetPresets(arg1, arg2) {
  return window['go']['main']['App']['GetPresets'](arg1, arg2);
}

export function InstallSTROnBox(arg1) {
  return window['go']['main']['App']['InstallSTROnBox'](arg1);
}

export function IsBoseStick(arg1) {
  return window['go']['main']['App']['IsBoseStick'](arg1);
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function ListMediaServers(arg1) {
  return window['go']['main']['App']['ListMediaServers'](arg1);
}

export function ListWiFiProfiles() {
  return window['go']['main']['App']['ListWiFiProfiles']();
}

export function Pause(arg1, arg2) {
  return window['go']['main']['App']['Pause'](arg1, arg2);
}

export function PlaySlot(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlaySlot'](arg1, arg2, arg3);
}

export function PlayURL(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PlayURL'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ProbeSetupAP() {
  return window['go']['main']['App']['ProbeSetupAP']();
}

export function PushWLANToBox(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PushWLANToBox'](arg1, arg2, arg3, arg4);
}

export function RebootBox(arg1, arg2) {
  return window['go']['main']['App']['RebootBox'](arg1, arg2);
}

export function SaveDiagnosticBundle(arg1, arg2) {
  return window['go']['main']['App']['SaveDiagnosticBundle'](arg1, arg2);
}

export function SelectBoxSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectBoxSource'](arg1, arg2, arg3);
}

export function SetBoxBass(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBoxBass'](arg1, arg2, arg3);
}

export function SetBoxLanguage(arg1, arg2) {
  return window['go']['main']['App']['SetBoxLanguage'](arg1, arg2);
}

export function SetBoxName(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBoxName'](arg1, arg2, arg3);
}

export function SetBoxVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBoxVolume'](arg1, arg2, arg3);
}

export function SetClockDisplay(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetClockDisplay'](arg1, arg2, arg3, arg4);
}

export function SetPreset(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetPreset'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Status(arg1, arg2) {
  return window['go']['main']['App']['Status'](arg1, arg2);
}

export function StickConfigs(arg1) {
  return window['go']['main']['App']['StickConfigs'](arg1);
}

export function StickVersion(arg1) {
  return window['go']['main']['App']['StickVersion'](arg1);
}

export function Stop(arg1, arg2) {
  return window['go']['main']['App']['Stop'](arg1, arg2);
}

export function SyncBoxPresets(arg1, arg2) {
  return window['go']['main']['App']['SyncBoxPresets'](arg1, arg2);
}

export function TrueFactoryReset(arg1) {
  return window['go']['main']['App']['TrueFactoryReset'](arg1);
}

export function TryWiFiPassword(arg1) {
  return window['go']['main']['App']['TryWiFiPassword'](arg1);
}

export function UpdateBoxAgent(arg1, arg2) {
  return window['go']['main']['App']['UpdateBoxAgent'](arg1, arg2);
}

export function VoteStation(arg1, arg2, arg3) {
  return window['go']['main']['App']['VoteStation'](arg1, arg2, arg3);
}

export function WriteNameConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteNameConfig'](arg1, arg2);
}

export function WriteRegionConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteRegionConfig'](arg1, arg2);
}

export function WriteStickFiles(arg1) {
  return window['go']['main']['App']['WriteStickFiles'](arg1);
}

export function WriteWLANConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteWLANConfig'](arg1, arg2, arg3);
}
