// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sticksetup} from '../models';
import {wifiprofiles} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function AppVersion():Promise<string>;

export function BoxAgentVersion(arg1:string,arg2:number):Promise<Record<string, string>>;

export function BoxSettings(arg1:string,arg2:number):Promise<Record<string, any>>;

export function BrowseLibrary(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.LibraryPage>;

export function CheckAppUpdate():Promise<Record<string, string>>;

export function CurrentWiFi():Promise<string>;

export function DeletePreset(arg1:string,arg2:number,arg3:number):Promise<void>;

export function DiscoverBoxes(arg1:number):Promise<Array<main.BoxInfo>>;

export function EjectDrive(arg1:string):Promise<void>;

export function ExportDiagnosticLogs(arg1:main.LogExportRequest):Promise<main.LogExportResult>;

export function FormatStick(arg1:string):Promise<void>;

export function GetAirplayOpt(arg1:string,arg2:number):Promise<Record<string, boolean>>;

export function GetBoxLanguage(arg1:string):Promise<string>;

export function GetClockDisplay(arg1:string):Promise<string>;

export function GetClockFormat24(arg1:string):Promise<boolean>;

export function GetLogFilePath():Promise<string>;

export function GetPresets(arg1:string,arg2:number):Promise<Array<main.Preset>>;

export function InstallSTROnBox(arg1:string):Promise<main.InstallResult>;

export function IsBoseStick(arg1:string):Promise<boolean>;

export function ListDrives():Promise<Array<sticksetup.Drive>>;

export function ListMediaServers(arg1:number):Promise<Array<main.LibraryServer>>;

export function ListWiFiProfiles():Promise<Array<wifiprofiles.Profile>>;

export function LogClientError(arg1:string):Promise<void>;

export function Pause(arg1:string,arg2:number):Promise<void>;

export function PlaySlot(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PlayURL(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function ProbeSetupAP():Promise<main.BoxInfo|boolean>;

export function PushWLANToBox(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SetupAPPushResult>;

export function RebootBox(arg1:string,arg2:number):Promise<void>;

export function ResolveStationLogo(arg1:string,arg2:Array<string>):Promise<string>;

export function SaveDiagnosticBundle(arg1:Array<string>,arg2:boolean):Promise<main.LogExportResult>;

export function SelectBoxSource(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetAirplayOpt(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetAppLocale(arg1:string):Promise<void>;

export function SetBoxBass(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetBoxLanguage(arg1:string,arg2:number):Promise<void>;

export function SetBoxName(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetBoxVolume(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetClockDisplay(arg1:string,arg2:boolean,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function SetPreset(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string,arg7:number):Promise<void>;

export function Status(arg1:string,arg2:number):Promise<string>;

export function StickConfigs(arg1:string):Promise<sticksetup.StickConfigs>;

export function StickVersion(arg1:string):Promise<string>;

export function Stop(arg1:string,arg2:number):Promise<void>;

export function StreamBitrate(arg1:string,arg2:number):Promise<number>;

export function SuggestBoxLanguage(arg1:string,arg2:string):Promise<number>;

export function SyncBoxPresets(arg1:string,arg2:number):Promise<Record<string, any>>;

export function TrueFactoryReset(arg1:string):Promise<main.TrueFactoryResetResult>;

export function TryWiFiPassword(arg1:string):Promise<string>;

export function UninstallSTR(arg1:string):Promise<main.UninstallSTRResult>;

export function UpdateBoxAgent(arg1:string,arg2:number):Promise<void>;

export function VoteStation(arg1:string,arg2:number,arg3:string):Promise<void>;

export function WriteLangConfig(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function WriteNameConfig(arg1:string,arg2:string):Promise<void>;

export function WriteRegionConfig(arg1:string,arg2:string):Promise<void>;

export function WriteStickFiles(arg1:string):Promise<Array<string>>;

export function WriteWLANConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
