// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sticksetup} from '../models';
import {wifiprofiles} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function AppVersion():Promise<string>;

export function BoxAgentVersion(arg1:string,arg2:number):Promise<Record<string, string>>;

export function BoxSettings(arg1:string,arg2:number):Promise<Record<string, any>>;

export function CheckAppUpdate():Promise<Record<string, string>>;

export function CurrentWiFi():Promise<string>;

export function DeletePreset(arg1:string,arg2:number,arg3:number):Promise<void>;

export function DiscoverBoxes(arg1:number):Promise<Array<main.BoxInfo>>;

export function EjectDrive(arg1:string):Promise<void>;

export function FormatStick(arg1:string):Promise<void>;

export function GetPresets(arg1:string,arg2:number):Promise<Array<main.Preset>>;

export function IsBoseStick(arg1:string):Promise<boolean>;

export function ListDrives():Promise<Array<sticksetup.Drive>>;

export function ListWiFiProfiles():Promise<Array<wifiprofiles.Profile>>;

export function Pause(arg1:string,arg2:number):Promise<void>;

export function PlaySlot(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PlayURL(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function RebootBox(arg1:string,arg2:number):Promise<void>;

export function SelectBoxSource(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetBoxBass(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetBoxName(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetBoxVolume(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetPreset(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function Status(arg1:string,arg2:number):Promise<string>;

export function StickConfigs(arg1:string):Promise<sticksetup.StickConfigs>;

export function StickVersion(arg1:string):Promise<string>;

export function Stop(arg1:string,arg2:number):Promise<void>;

export function SyncBoxPresets(arg1:string,arg2:number):Promise<Record<string, any>>;

export function TryWiFiPassword(arg1:string):Promise<string>;

export function UpdateBoxAgent(arg1:string,arg2:number):Promise<void>;

export function VoteStation(arg1:string,arg2:number,arg3:string):Promise<void>;

export function WriteNameConfig(arg1:string,arg2:string):Promise<void>;

export function WriteRegionConfig(arg1:string,arg2:string):Promise<void>;

export function WriteStickFiles(arg1:string):Promise<Array<string>>;

export function WriteWLANConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
